name: Cypress Tests 

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: |
                  npm install mocha mocha-junit-reporter --save-dev
                  npm install cypress-multi-reporters --save-dev
                  npm install mochawesome --save-dev
                  npm install mochawesome-merge --save-dev
                  npm install mochawesome-report-generator --save-dev
                  npm run build
          start: npm start 
          post: npm run report:merge
          report: npm run report:generate
                  
      - name: cypress-report
        # You may pin to the exact commit or the version.
        # uses: duynhanf/cypress-report@ce6bbdbf56f81503520be662de82e84f8901cda4
        uses: duynhanf/cypress-report@v2
        with: # number of milliseconds to wait
          milliseconds: 1000
      - name: Cypress report action
  # You may pin to the exact commit or the version.
  # uses: dmitry/cypress-report-action@739a256a823e7b6c79837673c124a655fe49a3e8
        uses: dmitry/cypress-report-action@1.0.0
        with:
    # Github token
         token: ${{ secrets.GITHUB_TOKEN }}
    # Title in the comment
         title: Cypress report
    # Should it be shown always or it should be deleted when there are no failures
         always: true
