name: Cypress Tests 

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
      - name: cypress-report
        # You may pin to the exact commit or the version.
        # uses: duynhanf/cypress-report@ce6bbdbf56f81503520be662de82e84f8901cda4
        uses: duynhanf/cypress-report@v2
        with: # number of milliseconds to wait
          milliseconds: 1000
